services:
  docs:
    build:
      context: .
      args:
        APP_NAME: docs
        PORT: 81
    ports:
      - "81:81"

  portal:
    build:
      context: .
      args:
        APP_NAME: portal
        PORT: 80
    ports:
      - "80:80"
